version: "3.5"

services:
  mysql:
    image: mysql:5.7
    networks:
      - sanook_app_net
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: "[6Pxitdv["
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: processor_machine
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "[6Pxitdv["
      MYSQL_ROOT_PASSWORD: root
    networks:
      - sanook_app_net

networks:
  sanook_app_net:
    driver: bridge
