version: "3.5"

services:
  mysql:
    image: mysql:5.7
    networks:
      - sanook_app_net
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: processor_machine
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sanook_app_net

networks:
  sanook_app_net:
    driver: bridge
